package com.pathdx.constant;

public enum AuditAction {
    LOGIN_SUCCESS,
    LOGIN_FAILED,
    CASE_ASSIGNED_BY_RULE,
    CASE_ASSIGNED_BY_ADMIN,
    REPORT_GENERATED,
    REPORT_DOWNLOADED,
    ANNOTATED_IMAGE_DOWNLOADED,
    ADDITIONAL_REQUEST_SUBMITTED,
    USER_ACCESS_UPDATED,
    REPORT_HEADER_MODIFIED,
    PASSWORD_CHANGED,
    PASSWORD_RESET,
    LOGGED_OUT,
    SETTING_ALLOCATION,
    SETTING_LAB_DETAILS_EDIT,
	SETTING_NOTIFICATION,
    PROFILE_EDIT
}
